apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-server-tls
  namespace: openshift-config
spec:
  isCA: false
  commonName: api.<cluster_base_domain>
  secretName: api-server-certs
  dnsNames:
  - api.<cluster_base_domain>
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare